# Generated by Django 6.0.1 on 2026-01-10 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=200)),
                ('ktp_image', models.ImageField(blank=True, upload_to='ktp/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='affiliates.affiliate')),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('bank_name_snapshot', models.CharField(max_length=100)),
                ('account_number_snapshot', models.CharField(max_length=50)),
                ('account_holder_snapshot', models.CharField(max_length=200)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('transfer_reference', models.CharField(blank=True, max_length=100)),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='affiliates.affiliate')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='commissions.bankaccount')),
            ],
            options={
                'db_table': 'payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('paid', 'Paid'), ('voided', 'Voided')], default='pending', max_length=20)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('voided_reason', models.CharField(blank=True, max_length=255)),
                ('matured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='affiliates.affiliate')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='orders.order')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='affiliates.referral')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_items', to='commissions.payout')),
            ],
            options={
                'db_table': 'commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['affiliate', 'status', 'created_at'], name='commissions_affilia_d8042e_idx'), models.Index(fields=['order'], name='commissions_order_i_46176b_idx')],
            },
        ),
    ]
