# Generated by Django 6.0.1 on 2026-01-10 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code (e.g., QURBAN2024)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount in Rupiah', max_digits=12)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('usage_limit', models.IntegerField(blank=True, help_text='Maximum number of times this coupon can be used (null = unlimited)', null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this coupon has been used')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=0, help_text='Minimum order amount required to use this coupon', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(help_text='Affiliate who owns this coupon', on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='affiliates.affiliate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='commissions_code_547bbc_idx'), models.Index(fields=['affiliate', 'is_active'], name='commissions_affilia_610fe0_idx')],
            },
        ),
    ]
