# Generated by Django 6.0.1 on 2026-01-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
