# Generated by Django 6.0.1 on 2026-01-10 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('tiktok', models.CharField(blank=True, max_length=100)),
                ('youtube', models.CharField(blank=True, max_length=200)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('primary_platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('blog', 'Website/Blog'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField(help_text='Why do you want to become an affiliate?')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected')),
                ('custom_commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'affiliates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('voided', 'Voided')], default='pending', max_length=20)),
                ('customer_name_masked', models.CharField(max_length=100)),
                ('customer_email_masked', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='affiliates.affiliate')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='orders.order')),
            ],
            options={
                'db_table': 'referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer_url', models.URLField(blank=True)),
                ('landing_page', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='affiliates.affiliate')),
            ],
            options={
                'db_table': 'referral_clicks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['affiliate', 'created_at'], name='referral_cl_affilia_323d74_idx')],
            },
        ),
    ]
