# Generated by Django 6.0.1 on 2026-01-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of these statistics')),
                ('clicks', models.IntegerField(default=0, help_text='Total clicks for this day')),
                ('conversions', models.IntegerField(default=0, help_text='Total conversions (orders) for this day')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Conversion rate percentage (conversions/clicks * 100)', max_digits=5)),
                ('commission_earned', models.DecimalField(decimal_places=0, default=0, help_text='Total commission earned this day', max_digits=12)),
                ('commission_matured', models.DecimalField(decimal_places=0, default=0, help_text='Total commission that matured this day', max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=0, default=0, help_text='Total order value from referrals this day', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='affiliates.affiliate')),
            ],
            options={
                'verbose_name': 'Daily Stat',
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['affiliate', 'date'], name='affiliates__affilia_2c78d3_idx'), models.Index(fields=['date'], name='affiliates__date_e065c6_idx')],
                'unique_together': {('affiliate', 'date')},
            },
        ),
    ]
