# Generated by Django 6.0.1 on 2026-01-10 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_dailystats'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['affiliate', 'status', 'created_at'], name='referrals_affilia_62a173_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['order'], name='referrals_order_i_1c969d_idx'),
        ),
    ]
