# Generated by Django 6.0.1 on 2026-01-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('kambing', 'Kambing'), ('sapi', 'Sapi')], max_length=20)),
                ('grade', models.CharField(blank=True, choices=[('a', 'Grade A'), ('b', 'Grade B'), ('premium', 'Premium')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('weight_min', models.DecimalField(decimal_places=1, help_text='Minimum weight in kg', max_digits=6)),
                ('weight_max', models.DecimalField(decimal_places=1, help_text='Maximum weight in kg', max_digits=6)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('shares_available', models.PositiveIntegerField(default=1, help_text='For sapi: 7 shares per animal')),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Affiliate commission %', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-is_featured', 'category', 'price'],
            },
        ),
    ]
